name: frap_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9
  - ipython
  - pip
  - numpy
  - aicsimageio
  - czifile
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - opencv
  - tqdm
  - pyside2
  - pyqtgraph
  - pip:
    - aicspylibczi>=3.0.5
